---
# RUN WITH:
# ansible-playbook --ask-become-pass install_apache.yml
#
- hosts: all
  become: true
  tasks:
    - name: update repository index
      apt:
        update_cache: yes
      when: ansible_distribution == ["Ubuntu", "Debian"]

    - name: install apache2 package
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == ["Ubuntu", "Debian"]

    - name: add php support for apache
      apt:
        name: libapache2-mod-php
      when: ansible_distribution == ["Ubuntu", "Debian"]

    - name: update repository index
      dnf:
        update_cache: yes
      when: ansible_distribution == ["Centos"]

    - name: install apache2 package
      dnf:
        name: httpd 
        state: latest
      when: ansible_distribution == ["Centos"]

    - name: add php support for apache
      dnf:
        name: php 
        state: latest
      when: ansible_distribution == ["Centos"]
