---
# RUN WITH:
# ansible-playbook --ask-become-pass install_apache.yml
#
- hosts: all
  become: true
  tasks:
    - name: update repository index Ubuntu/Debian
      apt:
        update_cache: yes
      when: ansible_distribution == ["Ubuntu", "Debian"]

    - name: install apache2 and php package for Ubuntu/Debian
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == ["Ubuntu", "Debian"]

    - name: update repository index Centos
      dnf:
        update_cache: yes
      when: ansible_distribution == ["Centos"]

    - name: install apache2 and php packages for Centos 
      dnf:
        name: 
          - httpd 
          - php
        state: latest
      when: ansible_distribution == ["Centos"]
