---
# RUN WITH:
# ansible-playbook --ask-become-pass install_apache.yml

- hosts: all
  become: true
  pre_tasks:
 
  - name: install updates (CentOS)
    when: ansible_distribution == "CentOS"
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
 
  - name: install updates (Ubuntu)
    when: ansible_distribution == "Ubuntu"
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
 
 
- hosts: WEB_SERVERS 
  become: true
  tasks:
 
  - name: install apache and php for Ubuntu servers
    when: ansible_distribution == "Ubuntu"
    tags: apache,apache2,ubuntu 
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
 
  - name: install apache and php for CentOS servers
    when: ansible_distribution == "CentOS"
    tags: apache,httpd,centos 
    dnf:
      name:
        - httpd
        - php
      state: latest
      
  - name: start and enable httpd (apache) on CentOS systems
    when: ansible_distribution == "CentOS"
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes

### COPY directory of ansibleBaseDirectory/files is assumed
  - name: copy default html file for site
    tags: apache,apache2,httpd 
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
        # Owner read/write Group read Other read

### TERRAFORM / WORKSTATIONS
- hosts: WORKSTATIONS 
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: DB_SERVERS 
  become: true
  tasks:
  
  - name: install db  package (CentOS)
    when: ansible_distribution == "CentOS"
    tags: mariadb,centos,db 
    dnf:
      name: mariadb
      state: latest

  - name: install db package (Ubuntu)
    when: ansible_distribution == "Ubuntu"
    tags: mariadb-server,mariadb,ubuntu 
    apt:
      name: mariadb-server
      state: latest

- hosts: FILE_SERVERS 
  become: true
  tasks:
  
  - name: install samba package 
    tags: samba
    package:
      name: samba 
      state: latest

