---
- hosts: ALL 
  become: true
  pre_tasks:

  - name: install updates (CentOS) not reported as change
    tags: always,dnf,noreport
    when: ansible_distribution == "CentOS"
    changed_when: false
    dnf:
      update_cache: yes
 
  - name: install updates (Ubuntu) not reported as change
    tags: always,apt,noreport
    when: ansible_distribution == "Ubuntu"
    changed_when: false
    apt:
      update_cache: yes


- hosts: ALL 
  become: true
  roles:
    - base

 - hosts: WORKSTATIONS
  become: true
  roles:
    - workstations
 
- hosts: WEB_SERVERS 
  become: true
  roles:
    - web_servers

- hosts: DB_SERVERS 
  become: true
  roles:
    - db_servers
  
- hosts: FILE_SERVERS 
  become: true
  roles:
    - file_servers
